import socket
import random
from ast import literal_eval


def intersection(list1,list2):
  list3 = [value for value in list1 if value in list2]
  list3.sort()
  list3 = list(dict.fromkeys(list3))
  return list3
serverList = []
N = 10
for i in range(N):
  serverList.append(random.randint(1,10))
s = socket.socket(socket.AF_INET,socket.SOCK_STREAM,0)

print('List generated by server: ', serverList)
host = socket.gethostbyname('localhost')

ports = 12345
portc = 32451

s.bind(('',ports))

s.listen(5)

while True:
  c,addr = s.accept()
  print('Incoming connection from ',addr)
  c.send(b'Thank you for connecting!')
  print(c.recv(1024))
  arrayLength = int(c.recv(1024).decode('utf-8'))
  clientInput = c.recv(arrayLength*1024).decode('utf-8')
  clientInput = literal_eval(clientInput)
  c.send(b'Press 1 for deduplication and 2 for set intersection')
  clientChoice = c.recv(1024).decode('utf-8')
  if clientChoice == '1':
    serverOutput = list(dict.fromkeys(clientInput))
    c.send(bytes(str(serverOutput).encode('UTF-8')))
  elif clientChoice == '2':
    serverOutput = intersection(clientInput,serverList)
    c.send(bytes(str(serverOutput).encode('UTF-8')))
  else:
    c.send(b'Please enter a valid choice!')
  c.close()


